### ISSUE TITLE
Three tabs trick for new line doesn't work for SCSS

### ISSUE THREAD

**Issue by pepelsbey** [hayaku/hayaku#166]
Type: `c → → →` in CSS and SCSS modes and compare.

CSS

``` css
p {
    color:#FFF;
    |
    }
```

SCSS

``` css
p {
    color:#FFF; |
    }
```
