### ISSUE TITLE
Content on the right from the caret dissapearing on enter/tab

### ISSUE THREAD

**Issue by kizu** [hayaku/hayaku#168]
If a caret is right after the curly brace and there is something after on that line, pressing enter or tab would “eat” that content.

Example:

``` CSS
.foo { width: 10px; height: 10px; }
```
