### ISSUE TITLE
Incorrect detecting of indentation in some cases

### ISSUE THREAD

**Issue by kizu** [hayaku/hayaku#195]
1. only prefixed in a block:
   
   ``` CSS
   .foo {
   width: 10px;
   }
   .bar {
   -webkit-border-radius: 10px;
           border-radius: 10px;|
   }
   ```
2. Abbreviation have whitespaces after: `bra|___`
